/**
 * Package for handling OpenAI API responses.
 */
package com.openaiapi;

import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents a response from the OpenAI API, containing metadata and generated choices.
 */
public class AIResponse {

	@JsonProperty("created")
	private int created;

	@JsonProperty("usage")
	private Usage usage;

	@JsonProperty("model")
	private String model;

	@JsonProperty("service_tier")
	private String serviceTier;

	@JsonProperty("id")
	private String id;

	@JsonProperty("choices")
	private List<ChoicesItem> choices;

	@JsonProperty("system_fingerprint")
	private Object systemFingerprint;

	@JsonProperty("object")
	private String object;

	/**
	 * Sets the creation timestamp.
	 * @param created the timestamp of response creation
	 */
	public void setCreated(int created){
		this.created = created;
	}

	/**
	 * Gets the creation timestamp.
	 * @return the creation timestamp
	 */
	public int getCreated(){
		return created;
	}

	/**
	 * Sets the usage information.
	 * @param usage the usage details
	 */
	public void setUsage(Usage usage){
		this.usage = usage;
	}

	/**
	 * Gets the usage details.
	 * @return the usage information
	 */
	public Usage getUsage(){
		return usage;
	}

	/**
	 * Sets the model name.
	 * @param model the model used
	 */
	public void setModel(String model){
		this.model = model;
	}

	/**
	 * Gets the model name.
	 * @return the model used
	 */
	public String getModel(){
		return model;
	}

	/**
	 * Sets the service tier.
	 * @param serviceTier the service tier level
	 */
	public void setServiceTier(String serviceTier){
		this.serviceTier = serviceTier;
	}

	/**
	 * Gets the service tier.
	 * @return the service tier level
	 */
	public String getServiceTier(){
		return serviceTier;
	}

	/**
	 * Sets the response ID.
	 * @param id the response ID
	 */
	public void setId(String id){
		this.id = id;
	}

	/**
	 * Gets the response ID.
	 * @return the response ID
	 */
	public String getId(){
		return id;
	}

	/**
	 * Sets the list of choices generated by the AI.
	 * @param choices the list of choices
	 */
	public void setChoices(List<ChoicesItem> choices){
		this.choices = choices;
	}

	/**
	 * Gets the list of choices.
	 * @return the list of choices
	 */
	public List<ChoicesItem> getChoices(){
		return choices;
	}

	/**
	 * Sets the system fingerprint.
	 * @param systemFingerprint the system fingerprint
	 */
	public void setSystemFingerprint(Object systemFingerprint){
		this.systemFingerprint = systemFingerprint;
	}

	/**
	 * Gets the system fingerprint.
	 * @return the system fingerprint
	 */
	public Object getSystemFingerprint(){
		return systemFingerprint;
	}

	/**
	 * Sets the object type.
	 * @param object the type of response object
	 */
	public void setObject(String object){
		this.object = object;
	}

	/**
	 * Gets the object type.
	 * @return the type of response object
	 */
	public String getObject(){
		return object;
	}

	/**
	 * Returns a string representation of the response object.
	 * @return a formatted string with response details
	 */
	@Override
	public String toString(){
		return "Response{" +
				"created = '" + created + '\'' +
				", usage = '" + usage + '\'' +
				", model = '" + model + '\'' +
				", service_tier = '" + serviceTier + '\'' +
				", id = '" + id + '\'' +
				", choices = '" + choices + '\'' +
				", system_fingerprint = '" + systemFingerprint + '\'' +
				", object = '" + object + '\'' +
				"}";
	}
}
